=== Gelio/teacher-results-xml-schema/teachers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="teachers"
    targetNamespace="http://www.mini.pw.edu.pl/ood"
    elementFormDefault="qualified"
    xmlns:teach="http://www.mini.pw.edu.pl/ood"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:complexType name="BaseStudent">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Surname" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:unsignedLong" />
  </xs:complexType>

  <xs:complexType name="BaseTask">
    <xs:attribute name="description" type="xs:string" />
    <xs:attribute name="maxPoints" type="xs:decimal" />
  </xs:complexType>

  
  
  <xs:complexType name="Teacher1Result">
    <xs:sequence>
      <xs:element name="Student" type="teach:BaseStudent" />
      <xs:element name="Points" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Teacher1Task">
    <xs:complexContent>
      <xs:extension base="teach:BaseTask">
        <xs:sequence>
          <xs:element name="Result" type="teach:Teacher1Result" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


  <xs:complexType name="Teacher2Task">
    <xs:complexContent>
      <xs:extension base="teach:BaseTask">
        <xs:sequence>
          <xs:element name="Points" type="xs:decimal" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Teacher2Results">
    <xs:sequence>
      <xs:element name="Task3" minOccurs="0" maxOccurs="1" type="teach:Teacher2Task" />
      <xs:element name="Task4" minOccurs="0" maxOccurs="1" type="teach:Teacher2Task" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Teacher2Student">
    <xs:complexContent>
      <xs:extension base="teach:BaseStudent">
        <xs:sequence>
          <xs:element name="Results" type="teach:Teacher2Results" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  

  
  <xs:element name="Teacher1Results">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Task1" type="teach:Teacher1Task" />
        <xs:element name="Task2" type="teach:Teacher1Task" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Teacher2Results">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Student" type="teach:Teacher2Student" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Gelio/teacher-results-xml-schema/teacher2.xml
<?xml version="1.0" encoding="utf-8"?>
<Teacher2Results xmlns="http://www.mini.pw.edu.pl/ood"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.mini.pw.edu.pl/ood teachers.xsd">
  <Student id="111111">
    <Name>Adrian</Name>
    <Surname>Abacki</Surname>
    <Results>
      <Task3 description="Stwórz diagram klas" maxPoints="25">
        <Points>21</Points>
      </Task3>
      <Task4 description="Stwórz diagram stanów" maxPoints="25">
        <Points>13</Points>
      </Task4>
    </Results>
  </Student>
  <Student id="222222">
    <Name>Bartosz</Name>
    <Surname>Babacki</Surname>
    <Results>
      <Task4 description="Stwórz diagram stanów" maxPoints="25">
        <Points>25  </Points>
      </Task4>
    </Results>
  </Student>
  <Student id="333333">
    <Name>Cyprian</Name>
    <Surname>Cabacki</Surname>
    <Results>
      <Task3 description="Stwórz diagram klas" maxPoints="25">
        <Points>25</Points>
      </Task3>
    </Results>
  </Student>
  <Student id="555555">
    <Name>Edward</Name>
    <Surname>Endecki</Surname>
    <Results>
      <Task4 description="Stwórz diagram stanów" maxPoints="25">
        <Points>2</Points>
      </Task4>
    </Results>
  </Student>
</Teacher2Results>

=== Gelio/teacher-results-xml-schema/Teacher results/teacher1.xml
<?xml version="1.0" encoding="utf-8"?>
<Teacher1Results xmlns="http://www.mini.pw.edu.pl/ood"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.mini.pw.edu.pl/ood teachers.xsd">
  <Task1 description="Zdeserializuj XMLe" maxPoints="25">
    <Result>
      <Student id="111111">
        <Name>Adrian</Name>
        <Surname>Abacki</Surname>
      </Student>
      <Points>10</Points>
    </Result>
    <Result>
      <Student id="444444">
        <Name>Dariusz</Name>
        <Surname>Dadacki</Surname>
      </Student>
      <Points>11</Points>
    </Result>
    <Result>
      <Student id="333333">
        <Name>Cyprian</Name>
        <Surname>Cabacki</Surname>
      </Student>
      <Points>12.5</Points>
    </Result>
  </Task1>
  <Task2 description="Transformuj XMLe" maxPoints="25">
    <Result>
      <Student id="111111">
        <Name>Adrian</Name>
        <Surname>Abacki</Surname>
      </Student>
      <Points>23</Points>
    </Result>
    <Result>
      <Student id="222222">
        <Name>Bartosz</Name>
        <Surname>Babacki</Surname>
      </Student>
      <Points>21</Points>
    </Result>
    <Result>
      <Student id="444444">
        <Name>Dariusz</Name>
        <Surname>Dadacki</Surname>
      </Student>
      <Points>17</Points>
    </Result>
  </Task2>
</Teacher1Results>
